apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-iamproxy-ingest-service-account
  namespace: prometheus
  annotations:
    eks.amazonaws.com/role-arn: <AMP_INGEST_ROLE_ARN>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: amp-iamproxy-query-service-account
  namespace: prometheus
  annotations:
    eks.amazonaws.com/role-arn: <AMP_QUERY_ROLE_ARN>
