apiVersion: v1
kind: Service
metadata:
  name: microservices-app-service
  namespace: microservices
  labels:
    app: microservices-app
spec:
  type: LoadBalancer
  selector:
    app: microservices-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    name: http
